#!/bin/sh

D8BIN=" ../../../out.gn/x64.release/d8 ";
TESTFILE1=" ../adder/simpleadd_d8.js ";
D8FLAGS=" --wasm_interpret_all
       --trace_wasm_interpreter 
	--trace_wasm_decoder     
	--trace_wasm_compiler    
	--trace_wasm_decode_time 
	--trace_wasm_streaming   
	--wasm_trace_memory      
	--trace_liftoff
";

$D8BIN $D8FLAGS $TESTFILE1
