#!/bin/sh

D8BIN=" ../../../out.gn/x64.release/d8 ";
TESTFILE1=" ../adder/simpleadd_d8.js ";
D8FLAGS=" --wasm_taint --taint_random=28  --taint_full_log --taint_log="/tmp/wasm.log"";

$D8BIN $D8FLAGS $TESTFILE1
