#!/bin/sh
emcc quicksortInt.c \
 -Os \
 -s WASM=1 \
 -s MODULARIZE=1 \
 -s DEMANGLE_SUPPORT=1 \
 -s ALLOW_MEMORY_GROWTH=1 \
 -s "EXPORTED_FUNCTIONS=['_quicksortInt']"  \
 -s "BINARYEN_METHOD='interpret-binary'" \
 -o quicksortInt.js
